# Generated by Django 4.0.2 on 2022-03-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('E-payment', 'E-payment')], default='Cash', max_length=120, verbose_name='Payment method')),
                ('price', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField()),
                ('payment_date', models.DateTimeField()),
            ],
        ),
    ]
