# Generated by Django 4.0.2 on 2022-03-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usersdata_firstname_alter_usersdata_lastname_and_more'),
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usersdata'),
        ),
    ]
