# Generated by Django 4.0.2 on 2022-03-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('airlines', '0003_remove_ticket_ticket_price_flight_flight_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_Date', models.DateTimeField()),
                ('flightdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usersdata')),
            ],
        ),
    ]
