# Generated by Django 4.0.2 on 2022-03-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destinationplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('Pokhara', 'Pokhara'), ('Janakpur', 'Janakpur'), ('Kathmandu', 'Kathmandu'), ('Lumbini', 'Lumbini')], max_length=120)),
                ('description', models.TextField()),
            ],
        ),
    ]
