# Generated by Django 4.0.2 on 2022-03-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('ticket_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('ticket_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_time', models.TimeField()),
                ('flight_number', models.CharField(max_length=50)),
                ('seat_number', models.PositiveIntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.ticket')),
            ],
        ),
    ]
