# Generated by Django 4.0.2 on 2022-03-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='ticket',
            new_name='tickets',
        ),
    ]
