# Generated by Django 4.0.2 on 2022-03-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_rename_ticket_flight_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(default='Buddha', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='ticket_price',
            field=models.PositiveIntegerField(default=3500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='departure_date',
            field=models.DateField(default='2022-03-13'),
            preserve_default=False,
        ),
    ]
