# Generated by Django 4.0.2 on 2022-03-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_remove_ticket_ticket_price_flight_flight_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_date',
            field=models.DateField(default='2022-03-12'),
            preserve_default=False,
        ),
    ]
