# Generated by Django 4.0.2 on 2022-03-20 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agentsAdress',
            new_name='agentsAddress',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='agents',
            new_name='agentsnames',
        ),
        migrations.AddField(
            model_name='agent',
            name='agentPrice',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='agentEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agentsContact',
            field=models.IntegerField(),
        ),
    ]
