# Generated by Django 4.0.2 on 2022-03-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(choices=[('Hotel Average', 'Hotel Average'), ('Hotel Plaza', 'Hotel Plaza'), ('Hotel Angel', 'Hotel Angel'), ('Hotel GreenOrchid', 'Hotel GreenOrchid')], max_length=120)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
    ]
